name             'cachet'
maintainer       'Benjamin Chrobot'
maintainer_email 'benjamin.blair.chrobot@gmail.com'
license          'all_rights'
description      'Installs/Configures cachet'
long_description 'Installs/Configures cachet'
version          '0.1.0'

depends          'ssl'
depends          'apache2'
depends          'nginx'
depends          'php'
depends          'php-fpm'
depends          'database'
depends          'mysql2_chef_gem'
depends          'mysql'
depends          'git'
depends          'nodejs'
depends          'composer'