name             'cachet'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures cachet'
long_description 'Installs/Configures cachet'
version          '0.1.0'

depends          'git'
depends          'nodejs'